services:
  db:
    image: postgres:16.1
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mage

  mage:
    build: .
    ports:
      - "6789:6789"
    volumes:
      - .:/app
    env_file:
      - .env
    environment:
      - POETRY_VIRTUALENVS_CREATE=false
    depends_on:
    - db

volumes:
  postgres_data: