triggers:
- description: null
  envs: []
  last_enabled_at: 2024-12-08 15:31:28.930404
  name: weekly run
  pipeline_uuid: weekly_streamer_stats
  schedule_interval: '@weekly'
  schedule_type: time
  settings: null
  sla: null
  start_time: 2024-12-09 08:00:00
  status: active
  variables: {}
